# Header
menu:
  首页: /
  archives: /archives
  投资理财: /tags/投资理财

rss: /atom.xml
title: 日记

author: note
aboutme: ~
fancybox: true
date_format:
  zh-CN: 'YYYY年MM月DD日'
  ja: 'YYYY年MM月DD日'
  en: 'YYYY-MM-DD'
socials:
  github: ""
  flickr: ""
  email: ""
  wechat: ""

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

#主题方案
highlight_theme: atom light

# widget behavior
archive_type: 'monthly'
show_count: true

disqus_shortname:

# Miscellaneous
google_analytics: ''
gauges_analytics:
favicon: /images/avatar.png
avatar: "/images/avatar.png"
twitter:
google_plus:
fb_admins:
fb_app_id:
